data class Student(var name: String, var age: Int)

fun main(args: Array<String>) {
    val mazengo = Student("Stef D.", 19)
    val msalato = Student("Wendo Kasa", 17)

    //check autogenerated methods

    println("Mazengo Object is $mazengo")
    println("Mazengo toString is ${mazengo.toString()}")
    println("Mazengo HashCode is ${mazengo.hashCode()}")
    println("Mazengo Comparison with itself ${mazengo.equals(mazengo)}")
    println("Mazengo Comparison with Msazengo ${mazengo.equals(msalato)}")

    //copy
    val jangwani = msalato.copy()
    val azania = mazengo.copy("Hassan Omary")

    println("Jangwani toString is ${jangwani.toString()}")
    println("Azania toString is ${azania.toString()}")
}